<x-layout>
    
<style>
    @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap");


    .heartbeat {
	-webkit-animation: heartbeat 1.5s linear infinite ;
	        animation: heartbeat 1.5s linear infinite ;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-25 22:56:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: center center;
            transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91);
            transform: scale(0.91);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98);
            transform: scale(0.98);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87);
            transform: scale(0.87);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
}


.card {
	padding: 15px;
	width: 350px;
	background: #4f747d;
	border-radius: 5%;
	text-align: center;
	
	user-select: none;
}

.cover-photo {
    margin-left: auto;
    margin-right: auto;
}

.profile {
	width: 300px;
	border-radius: 5%;
}

.profile-name {
    margin-top: 5px;
    font-weight: bold;
	font-size: 20px;
	color: #fff;
}


.btn {
	margin: 30px 15px;
	background: #7ce3ff;
	padding: 10px 25px;
	border-radius: 3px;
	border: 1px solid #7ce3ff;
	font-weight: bold;
	font-family: Montserrat;
	cursor: pointer;
	color: #222;
	transition: 0.2s;
}


.rubberBand {
  animation-name: rubberBand;
  animation-duration: 2s;
  animation-fill-mode: both;
  }
  
  @keyframes rubberBand {
  0% {
  -webkit-transform: scale3d(1, 1, 1);
  transform: scale3d(1, 1, 1);
  }
  30% {
  -webkit-transform: scale3d(1.25, 0.75, 1);
  transform: scale3d(1.25, 0.75, 1);
  }
  40% {
  -webkit-transform: scale3d(0.75, 1.25, 1);
  transform: scale3d(0.75, 1.25, 1);
  }
  50% {
  -webkit-transform: scale3d(1.15, 0.85, 1);
  transform: scale3d(1.15, 0.85, 1);
  }
  65% {
  -webkit-transform: scale3d(.95, 1.05, 1);
  transform: scale3d(.95, 1.05, 1);
  }
  75% {
  -webkit-transform: scale3d(1.05, .95, 1);
  transform: scale3d(1.05, .95, 1);
  }
  100% {
  -webkit-transform: scale3d(1, 1, 1);
  transform: scale3d(1, 1, 1);
  }
  } 
  
  .demo-wrap {
  overflow: hidden;
  position: relative;
}

.demo-bg {
        border-radius: 50%;
  opacity: 0.2;
  position: absolute;
  right: 0;
  top: 0;
  width: 50%;
  height: 100%;
}

.demo-content {
  position: relative;
}


</style>
    <script>
        $(document).ready(function() {
            $("#managemodal").modal('show');
        });
    </script>

    @include('partials._search')

    <div class="lg:grid lg:grid-cols-2 gap-4 space-y-4 md:space-y-0 mx-4">

        @if (count($listings) != 0)

        @foreach ($listings as $listing)
        <x-listing-card :listing="$listing" />
        @endforeach
        @else
        <p>No listings found</p>
        @endif


    </div>


    <!-- official index-->
    <div class="modal fade" id="managemodal" tabindex="-1" aria-labelledby="managemodalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                        <img src="{{asset('/logo/'.$label->logo)}}" class="w-20 h-20 mr-5">
                    <h1 class="modal-title" id="managemodalLabel" style="font-weight: bold;">Officials of {{$label->location}}, Barangay {{$label->brgname}}</h1>
                   
                    
                    <button type="button" class="btn-close" aria-label="Close"><i class="solid fa fa-close" onclick="history.back()"></i></button>
                   
                </div>
              
                
                <div class="modal-body bg-black text-white" >

                        

<div id="carouselExampleControls" class="carousel slide"   >
        <div class="carousel-inner">
                
               
                <div class="carousel-item active" >
                        <section style="width: 50%; margin-left: auto; margin-right:auto;" >
                                <div class="align-items-center" style="text-align: center; padding-top:100px; padding-bottom:100px;">
                                    
                                    
                                    <div class="text-white rubberBand">
                                        <span style="font-size: 30px;">
                                                <h1 style="font-weight: bold; text-transform:uppercase">This Officials are based on the User Inputs.</h1>
                                               
                                        </span>
                                        
                                    </div>
                                  </div>
                                </section>

                      </div>
                      
                @foreach($officials as $data  )
          <div class="carousel-item " >
                <div class="demo-wrap">
                        <img
                        class="demo-bg"
                        src="{{ asset('/logo/'.$label->logo) }}"
                        alt="Barangay Logo"
                      >
                        <div class="demo-content">
                       
                <section style="width: 80%; margin-left: auto; margin-right:auto;" >
                        
                                <div class="row align-items-center">
                                    <div class="col ">

                                    <div class="card " style="margin-left: auto; margin-right: auto;">
                                
                                <div class="cover-photo heartbeat">
                                <img src="{{ asset('/profile/'.$data->pp) }}" class="profile" >
                                </div>
                                <h1 class="profile-name">{{$data->fname}} {{$data->lname}}</h1>
                                <p>{{$data->sex}}</p>
                                
                                <button class="btn">{{$data->position}}</button>
                                
                                </div>
                                
                                    </div>
                                    <div class="col">
                                    <div class="text-white ">
                                        
                                        <span style="font-size: 30px;">
                                                <h1 style="font-weight: bold; text-transform:uppercase">Contact </h1>
                                                
                                                <p>{{$data->contact}}</p>
                                        </span>
                                        <hr style="margin-bottom: 10px; margin-top: 10px;">
                                        <span style="font-size: 30px;" >
                                                <h1 style="font-weight: bold; text-transform:uppercase">Location</h1>
                                                <p>{{$data->location}}</p>
                                        </span>
                                        <hr style="margin-bottom: 10px; margin-top: 10px;">
                                        <span style="font-size: 30px">
                                                <h1 style="font-weight: bold; text-transform:uppercase">Barangay</h1>
                                                <p>{{$data->brgname}}</p>
                                        </span>
                                        <hr style="margin-bottom: 10px; margin-top: 10px;">
                                        <span style="font-size: 30px">
                                                <h1 style="font-weight: bold; text-transform:uppercase">Location Link</h1>
                                                <a href="{{$maplink}}"><p>Click Me!</p></a>
                                        </span>
                                </div>
                                    </div>
                                  </div>
                                </section>

              </div>
        </div>
</div>
          @endforeach
          </div>
          
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>


 {{-- end of modal body --}}
</div>
<x-flash-message />
                    </div>
                </div>
                <div class="modal-footer">


                    

                </div>
            </div>

        </div>
    </div>
    </div>




</x-layout>